-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/

-- settings.bind
hl.bind("SUPER + return", (hl.dsp.exec_cmd( "kitty" )), {})
hl.bind("SUPER + Q", (hl.dsp.exec_cmd( "librewolf" )), {})
hl.bind("SUPER + P", (hl.dsp.exec_cmd( "hyprpicker" )), {})
hl.bind("SUPER + E", (hl.dsp.exec_cmd( "kitty yazi" )), {})
hl.bind("SUPER + D", (hl.dsp.exec_cmd( "wofi --show drun" )), {})
hl.bind("SUPER + C", (hl.dsp.window.close()), {})
hl.bind("SUPER + F", (hl.dsp.window.fullscreen()), {})
hl.bind("SUPER + M", (hl.dsp.exec_cmd( "hyprlock" )), {})
hl.bind("SUPER + SHIFT + F", (hl.dsp.window.float({ action = "toggle" })), {})
hl.bind("SUPER + V", (hl.dsp.exec_cmd( "kitty --class clipse -e clipse" )), {})
hl.bind("SUPER + N", (hl.dsp.exec_cmd( "swaync-client -t" )), {})
hl.bind("SUPER + SHIFT + N", (hl.dsp.exec_cmd( "kitty impala" )), {})
hl.bind("XF86AudioRaiseVolume", (hl.dsp.exec_cmd( "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioLowerVolume", (hl.dsp.exec_cmd( "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioMute", (hl.dsp.exec_cmd( "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioMicMute", (hl.dsp.exec_cmd( "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86MonBrightnessUp", (hl.dsp.exec_cmd( "brightnessctl -d intel_backlight set 5%+" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86MonBrightnessDown", (hl.dsp.exec_cmd( "brightnessctl -d intel_backlight set 5%-" )), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioNext", (hl.dsp.exec_cmd( "playerctl next" )), {
  ["locked"] = true
})
hl.bind("XF86AudioPause", (hl.dsp.exec_cmd( "playerctl play-pause" )), {
  ["locked"] = true
})
hl.bind("XF86AudioPlay", (hl.dsp.exec_cmd( "playerctl play-pause" )), {
  ["locked"] = true
})
hl.bind("XF86AudioPrev", (hl.dsp.exec_cmd( "playerctl previous" )), {
  ["locked"] = true
})
hl.bind("SUPER + h", (hl.dsp.focus({ direction = "left" })), {})
hl.bind("SUPER + l", (hl.dsp.focus({ direction = "right" })), {})
hl.bind("SUPER + k", (hl.dsp.focus({ direction = "up" })), {})
hl.bind("SUPER + j", (hl.dsp.focus({ direction = "down" })), {})
hl.bind("SUPER + 1", (hl.dsp.focus({ workspace = 1 })), {})
hl.bind("SUPER + 2", (hl.dsp.focus({ workspace = 2 })), {})
hl.bind("SUPER + 3", (hl.dsp.focus({ workspace = 3 })), {})
hl.bind("SUPER + 4", (hl.dsp.focus({ workspace = 4 })), {})
hl.bind("SUPER + SHIFT + 1", (hl.dsp.window.move({ workspace = 1 })), {})
hl.bind("SUPER + SHIFT + 2", (hl.dsp.window.move({ workspace = 2 })), {})
hl.bind("SUPER + SHIFT + 3", (hl.dsp.window.move({ workspace = 3 })), {})
hl.bind("SUPER + SHIFT + 4", (hl.dsp.window.move({ workspace = 4 })), {})
hl.bind("SUPER + SHIFT + h", (hl.dsp.focus({ workspace = "e-1" })), {})
hl.bind("SUPER + SHIFT + l", (hl.dsp.focus({ workspace = "e+1" })), {})
hl.bind("SUPER + SHIFT + CTRL + h", (hl.dsp.window.move({ workspace = "e-1" })), {})
hl.bind("SUPER + SHIFT + CTRL + l", (hl.dsp.window.move({ workspace = "e+1" })), {})
hl.bind("SUPER + SHIFT + k", (hl.dsp.layout( "swapcol l" )), {})
hl.bind("SUPER + SHIFT + j", (hl.dsp.layout( "swapcol r" )), {})
hl.bind("SUPER + SHIFT + CTRL + k", (hl.dsp.window.move({ monitor = "+1" })), {})
hl.bind("SUPER + SHIFT + CTRL + j", (hl.dsp.window.move({ monitor = "-1" })), {})
hl.bind("SUPER + CTRL + h", (hl.dsp.layout( "colresize -conf" )), {})
hl.bind("SUPER + CTRL + l", (hl.dsp.layout( "colresize +conf" )), {})
hl.bind("SUPER + CTRL + k", (hl.dsp.layout( "expel" )), {})
hl.bind("SUPER + CTRL + j", (hl.dsp.layout( "consume" )), {})
hl.bind("SHIFT + Print", (hl.dsp.exec_cmd( "hyprshot -m region $(date +%Y%m%d_%H%M%S).png" )), {})
hl.bind("SUPER + Print", (hl.dsp.exec_cmd( "hyprshot -m window $(date +%Y%m%d_%H%M%S).png" )), {})
hl.bind("Print", (hl.dsp.exec_cmd( "hyprshot -m output $(date +%Y%m%d_%H%M%S).png" )), {})
hl.bind("SUPER + mouse:272", (hl.dsp.window.drag()), {
  ["mouse"] = true
})
hl.bind("SUPER + mouse:273", (hl.dsp.window.resize()), {
  ["mouse"] = true
})

-- settings.config
hl.config({
  ["decoration"] = {
    ["shadow"] = {
      ["color"] = "rgba(282a3699)"
    }
  },
  ["general"] = {
    ["col.active_border"] = "rgb(80bfff)",
    ["col.inactive_border"] = "rgb(6272a4)"
  },
  ["group"] = {
    ["col.border_active"] = "rgb(80bfff)",
    ["col.border_inactive"] = "rgb(6272a4)",
    ["col.border_locked_active"] = "rgb(8be9fd)",
    ["groupbar"] = {
      ["col.active"] = "rgb(80bfff)",
      ["col.inactive"] = "rgb(6272a4)",
      ["text_color"] = "rgb(f8f8f2)"
    }
  },
  ["input"] = {
    ["follow_mouse"] = 1,
    ["kb_layout"] = "us",
    ["touchpad"] = {
      ["natural_scroll"] = true
    }
  },
  ["misc"] = {
    ["background_color"] = "rgb(282a36)"
  }
})

-- settings.monitor
hl.monitor({
  ["mode"] = "2560x1600@165",
  ["output"] = "eDP-1",
  ["position"] = "1600x0",
  ["scale"] = "1.6",
  ["vrr"] = 2
})
hl.monitor({
  ["mode"] = "2560x1440@144",
  ["output"] = "DP-1",
  ["position"] = "0x0",
  ["scale"] = "1.6",
  ["vrr"] = 2
})
hl.monitor({
  ["mode"] = "preferred",
  ["output"] = "",
  ["position"] = "auto",
  ["scale"] = "1.6"
})

-- settings.on
hl.on("hyprland.start", (function()
						hl.exec_cmd("dbus-update-activation-environment --systemd --all")
						hl.exec_cmd("polkit-agent")
						hl.exec_cmd("rfkill unblock bluetooth")
						hl.exec_cmd("hyprlock")
						hl.exec_cmd("awww-daemon")
						hl.exec_cmd("bash -c 'sleep 0.5; awww img --transition-type center --transition-angle 30 --transition-step 90 --transition-fps 60 --transition-duration 1 ~/nixos-dotfiles/assets/wallpapers/wallpaper.jpg'")
						hl.exec_cmd("swaync")
            hl.exec_cmd("bash -c 'sleep 3; waybar'")
						--hl.exec_cmd("bash -c 'sleep 3; pkill waybar; if hyprctl monitors | grep -q DP-1; then waybar -c ~/.config/waybar/config-monitor; else waybar -c ~/.config/waybar/config-laptop; fi'")
					end))

-- extraConfig
			hl.config({ xwayland = { force_zero_scaling = true } })
			hl.config({ cursor = { no_hardware_cursors = true } })

			hl.config({
				general = {
					layout  = "scrolling", --Niri like scrolling perfection
					gaps_in     = 8,
					gaps_out    = 16,
					border_size = 0,
					col = {
						active_border   = "rgba(3f3f68ff)",
						inactive_border = "rgba(3f3f68aa)",
					},
				},
			})

			hl.config({
				scrolling = {
					fullscreen_on_one_column = true,
					column_width             = 0.5,
					follow_focus             = true,
					follow_min_visible       = 0,
					wrap_focus               = true,
					explicit_column_widths   = "0.333, 0.5, 0.9, 1.0",
				},
			})
			
			hl.config({
        decoration = {
          rounding       = 10,
          rounding_power = 2, 

          active_opacity   = 0.850000,
          inactive_opacity = 0.850000,

          blur = {
            enabled  = true,
						new_optimizations = true,
            size     = 4,
            passes   = 2,
          },
        },
      })

			hl.config({ misc = { background_color = "rgb(0, 0, 0)" } })

			hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true, persistent = true })
			hl.workspace_rule({ workspace = "2", monitor = "DP-1", persistent = true })
			hl.workspace_rule({ workspace = "3", monitor = "eDP-1", persistent = true })
			hl.workspace_rule({ workspace = "4", monitor = "eDP-1", persistent = true })

			hl.window_rule({ match = { class = "clipse" }, float = true })
			hl.window_rule({ match = { class = "clipse" }, size = { 622, 652 } })

			hl.curve("snappy", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1} } })
			hl.animation({ leaf = "windows",    enabled = true, speed = 3, bezier = "snappy" })

			--snappy workspace switching
			hl.animation({ leaf = "workspaces", enabled = false })

			--hotplug waybar
			-- hl.on("monitor.added", function(m)
			-- 		hl.exec_cmd("pkill waybar")
			-- 		if m.name == "DP-1" then
			-- 				hl.exec_cmd("bash -c 'sleep 1 && waybar -c ~/.config/waybar/config-monitor'")
			-- 		else
			-- 				hl.exec_cmd("bash -c 'sleep 1 && waybar -c ~/.config/waybar/config-laptop'")
			-- 		end
			-- end)

			-- hl.on("monitor.removed", function(m)
			-- 		hl.exec_cmd("pkill waybar")
			-- 		hl.exec_cmd("bash -c 'sleep 1 && waybar -c ~/.config/waybar/config-laptop'")
			-- end)
      
		
