animations {
  fade_in {
    bezier=easeOutQuint
    duration=300
  }

  fade_out {
    bezier=easeOutQuint
    duration=300
  }
  enabled=true
}

background {
  blur_passes=3
  blur_size=8
  brightness=0.800000
  path=~/nixos-dotfiles/assets/wallpapers/wallpaper3.jpg
}

general {
  hide_cursor=false
  ignore_empty_input=true
}

image {
  monitor=
  size=120
  border_color=rgba(1a1a1aee)
  border_size=2
  halign=center
  path=~/nixos-dotfiles/assets/pfp.png
  position=0, -20
  rounding=-1
  valign=center
}

input-field {
  monitor=
  size=280, 55
  dots_center=true
  fade_on_empty=false
  font_color=rgba(80bfffff)
  inner_color=rgba(1a1a1aee)
  outer_color=rgba(80bfff00)
  outline_thickness=2
  placeholder_text=  Password...
  position=0, -200
}

label {
  monitor=
  color=rgba(80bfffff)
  font_size=70
  halign=center
  position=0, 350
  text=cmd[update:1000] echo "$(date +"%A")"
  valign=center
}

label {
  monitor=
  color=rgba(f8f8f2)
  font_size=36
  halign=center
  position=0, 260
  text=cmd[update:1000] echo "$(date +"%d %B")"
  valign=center
}

label {
  monitor=
  color=rgba(f8f8f2)
  font_size=30
  halign=center
  position=0, 210
  text=cmd[update:1000] echo "$(date +"%H:%M")"
  valign=center
}

label {
  monitor=
  color=rgba(f8f8f2)
  font_size=16
  halign=center
  position=0, -120
  text=  $USER
  valign=center
}

label {
  monitor=
  color=rgba(f8f8f2)
  font_family=Symbols Nerd Font
  font_size=38
  halign=center
  onclick=reboot
  position=0, 120
  text= 󰜉 
  valign=bottom
}

label {
  monitor=
  color=rgba(80bfffff)
  font_family=Symbols Nerd Font
  font_size=38
  halign=center
  onclick=shutdown now
  position=150, 120
  text= 󰐥 
  valign=bottom
}

label {
  monitor=
  color=rgba(f8f8f2)
  font_family=Symbols Nerd Font
  font_size=38
  halign=center
  onclick=systemctl suspend
  position=-150, 120
  text= 󰤄 
  valign=bottom
}
